### ISSUE TITLE
pollfish serveys 

### ISSUE THREAD

**Issue by boshi1** [pollfish/react-native-plugin-pollfish#7]
Pollfish survey not available.even with release mode (false).
it is impossible to test.

**Comment by boshi1** [comment]
"react": "17.0.2",
    "react-native": "0.66.2",
    "react-native-plugin-pollfish": "^2.0.7",

 var params = new RNPollfish.Builder('12f2f406-***********f181557a', null);
   params.indicatorPosition(RNPollfish.Position.topLeft).releaseMode(false).rewardInfo({
           rewardName: 'Points',
           rewardConversion: 1.3
       });

**Comment by fotism23** [comment]
Please try removing the `rewardInfo` definition. This exists in the documentation and the example project for showcasing the API usage. We are aware that this may have caused some confusion and we are in the process of updating our documentation accordingly. Please but keep in mind, if rewardInfo is set, you will have to calculate and define the correct signature in order to receive surveys. If your use case does not require a dynamic `rewardValue` you can define a static one through the Pollfish Publisher dashboard.

**Comment by boshi1** [comment]
thank you it worked, another bug i noticed is that the app freezes when doing the following
on android
showSurvery()=>{RNPollfish.show();initSurvery();} in the same line

**Comment by fotism23** [comment]
Hello @boshi1 
It is not expected to reinitialize Pollfish surveys right after `show` invocation. By calling init any previous visible panel will be dismissed.

**Comment by fotism23** [comment]
Hello @boshi1 
Did this resolve your issue or will you need further support?

**Comment by boshi1** [comment]
Yes,thank you it is working as expected

**Comment by umerdogar** [comment]
var builder = new RNPollfish.Builder(
    "7****5c-4455*************db5",
    null
  );

  builder.indicatorPosition(RNPollfish.Position.topLeft).releaseMode(false);
  builder.indicatorPadding(28);
  builder.releaseMode(false);

  RNPollfish.isPollfishPresent((isPollfishPresent) => {
    console.log(
      isPollfishPresent ? "Pollfish is available" : "Pollfish is not available"
    );
  });

  var params = builder.build();

  RNPollfish.init(params);

  console.log("RNPollfish.init(params)", params);
  RNPollfish.addEventListener(
    RNPollfish.PollfishUserNotEligibleListener,
    (a) => {
      console.log("Pollfish User Not Eligible", a);
    }
  );
  
  
  This is my code, i cant see anything in my app. It says Pollfish is not avaiable
